In [1]:
import torch
import torch.nn as nn
import copy
from icecream import ic

/home/jinjun/miniconda3/envs/quartz/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
net1 = nn.Linear(3,5).to('cuda:2')
ic(net1.weight.device)
net2 = copy.deepcopy(net1)
ic(net2.weight.device)

ic| net1.weight.device: device(type='cuda', index=2)
ic| net2.weight.device: device(type='cuda', index=2)


device(type='cuda', index=2)

In [8]:
net3 = net1

ic(net3.weight)

net1.weight.data = net1.weight.data + 100

ic(net3.weight)

ic| net3.weight: Parameter containing:
                 tensor([[-0.5693,  0.4885, -0.2683],
                         [-0.0751,  0.0521,  0.1915],
                         [-0.2107, -0.3562,  0.1439],
                         [ 0.4568, -0.3257,  0.2844],
                         [ 0.4334, -0.1284,  0.5170]], device='cuda:2', requires_grad=True)
ic| net3.weight: Parameter containing:
                 tensor([[ 99.4307, 100.4885,  99.7317],
                         [ 99.9249, 100.0521, 100.1915],
                         [ 99.7893,  99.6438, 100.1439],
                         [100.4568,  99.6743, 100.2844],
                         [100.4334,  99.8717, 100.5170]], device='cuda:2', requires_grad=True)


Parameter containing:
tensor([[ 99.4307, 100.4885,  99.7317],
        [ 99.9249, 100.0521, 100.1915],
        [ 99.7893,  99.6438, 100.1439],
        [100.4568,  99.6743, 100.2844],
        [100.4334,  99.8717, 100.5170]], device='cuda:2', requires_grad=True)